version: 2.1

orbs:
  maven: "circleci/maven@1.0.3"

#executors:
#  java:
#    description: "foo"
#    docker: "cimg/openjdk:8"

#jobs: {}

workflows:
  version: 2
  "java-build":
    jobs:
      - "maven/test":
          command: "clean verify site"
#        executor: "java"
#        pre-steps: []
#        post-steps: []
#      - "site":
#        requires:
#          - "verify"
#        command: "site"
#        executor: "java"
