version: 2.1

orbs:
  maven: "circleci/maven@1.0.3"

executors:
  "jdk":
    description: "OpenJDK 8"
    docker:
      - image: "cimg/openjdk:8.0"

#jobs: {}

workflows:
  version: 2
  "java-build":
    jobs:
      - "maven/test":
        command: "clean verify site"
        executor: "jdk"
        post-steps:
          - "store_artifacts":
            path: "target"
